/* GENERATED by src/build.py from the app's own code — do not edit.
   Run by functions/model.js in a sandbox; see server_model() in build.py. */
const P = SEED.P, TPL = SEED.TPL, POOL0 = SEED.POOL, YEARS = SEED.Y;
const NP = P.length;
const HIST_COUNT = SEED.T.length;
let CLUBS = SEED.C.slice();
const PC = i => "var(--p" + i + ")";

const CLUBCOL = {
  "באיירן":"#DC052D", "ברצלונה":"#A50044", "פסז":"#1D4E96", "ליברפול":"#C8102E",
  "ריאל":"#E8CE6A", "סיטי":"#6CABDD", "ארסנל":"#EF0107", "אתלטיקו":"#CB3524",
  "צרפת":"#3D6BB5", "פורטוגל":"#0B8A4A", "ברזיל":"#E5CE00", "אנגליה":"#E0424F",
  "ספרד":"#D4232F", "ארגנטינה":"#7EBBE8", "גרמניה":"#9AA3AC"
};
/* a stable fallback hue for a club the user adds later */
function clubCol(name) {
  if (CLUBCOL[name]) return CLUBCOL[name];
  let h = 0; for (let i = 0; i < name.length; i++) h = (h * 31 + name.charCodeAt(i)) % 360;
  return "hsl(" + h + " 52% 58%)";
}
function clubIdx(name) {
  name = (name || "").trim();
  let i = CLUBS.indexOf(name);
  if (i < 0) { CLUBS.push(name); i = CLUBS.length - 1; }
  return i;
}

/* ---------- helpers ---------- */
const el = (t, c, h) => { const n = document.createElement(t); if (c) n.className = c; if (h != null) n.innerHTML = h; return n; };
const esc = s => String(s).replace(/[&<>"]/g, c => ({ "&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;" }[c]));
const f1 = n => (Math.round(n * 10) / 10).toFixed(1);
const f2 = n => (Math.round(n * 100) / 100).toFixed(2);
const nf = n => n.toLocaleString("he-IL");
const sgnTxt = n => (n > 0 ? "+" : "") + n;
const sgn = n => '<span class="ltr">' + sgnTxt(n) + "</span>";
const sgn1 = v => '<span class="ltr">' + (v > 0 ? "+" : "") + f1(v) + "</span>";
const sgnF2 = v => '<span class="ltr">' + (v > 0 ? "+" : "") + f2(v) + "</span>";
const scoreTxt = (a, b) => '<span class="ltr">' + a + ":" + b + "</span>";
const plate = (i, cls) => '<span class="plate ' + (cls || "") + '" style="--c:' + PC(i) + '"><i class="dot"></i>' + esc(P[i]) + "</span>";
const plateFace = (i, cls) => '<span class="plate ' + (cls || "") + '" style="--c:' + PC(i) + '">' +
  (photoOf(i) ? '<i class="pface pf' + i + '"></i>' : '<i class="dot"></i>') + esc(P[i]) + "</span>";
function installFaceStyles() {
  let st = document.getElementById("faceCss");
  if (!st) { st = el("style"); st.id = "faceCss"; document.head.appendChild(st); }
  st.textContent = P.map((_, i) => {
    const f = photoOf(i);
    return f ? ".pf" + i + "{background-image:url(" + f + ")}" : "";
  }).filter(Boolean).join("\n");
}
const clubTag = ci => { const n = CLUBS[ci] || "—"; return '<span class="club" style="--c:' + clubCol(n) + '"><i class="cdot"></i>' + esc(n) + "</span>"; };
function textInput(value, ph) {
  const i = el("input");
  i.type = "text";
  i.autocomplete = "off";
  i.spellcheck = false;
  i.setAttribute("autocorrect", "off");
  i.setAttribute("autocapitalize", "off");
  i.setAttribute("data-1p-ignore", "true");
  i.setAttribute("data-lpignore", "true");
  if (value != null) i.value = value;
  if (ph) i.placeholder = ph;
  return i;
}
const shuffle = a => { for (let i = a.length - 1; i > 0; i--) { const j = Math.floor(Math.random() * (i + 1)); [a[i], a[j]] = [a[j], a[i]]; } return a; };

/* ---------- the live set of tournaments ---------- */
let LIVE = {};            // id -> tournament record kept in the store
let CLUB_POOL = POOL0.slice();
let TS = [];              // every tournament, all seasons, chronological
let TSS = [];             // the ones in the season now on screen
let SEASONS = [{ id: 0, name: "עונה 1" }];
let SCOPE = 0;            // season id, or "all"
let CARRY = null;         // last season's aggregate, shown while a new season is empty
let S, PAIR, H2H, TEAM, perT, ORDER, MAXAPP, totGoals, totMatches, drawnMatches, LAST;
let DUEL, LOG, CHEM;      // pair-vs-pair, the per-player match log, chemistry
const seasonById = id => SEASONS.find(s => s.id === id) || SEASONS[0];
const latestSeason = () => SEASONS.reduce((a, b) => (b.id > a.id ? b : a), SEASONS[0]).id;
const activeSeason = () => (SCOPE === "all" ? latestSeason() : SCOPE);
const uid = (season, num) => (season === 0 ? num : season * 1000 + num);
function nextNum(season) {
  const ns = TS.filter(t => t.season === season).map(t => t.num);
  return ns.length ? Math.max.apply(null, ns) + 1 : 1;
}

function decorate(t) {
  t.teamOf = {}; t.d.forEach(([p, c]) => { t.teamOf[p] = c; });
  t.players = t.d.map(x => x[0]);
  t.size = t.players.length;
  /* standings are always derived from the results, never stored */
  const acc = {}; t.players.forEach(p => { acc[p] = { p, g:0, w:0, dr:0, l:0, pts:0, gf:0, ga:0 }; });
  t.m.forEach(m => {
    const [h1, h2, ht, a1, a2, at, hg, ag] = m;
    if (hg == null || ag == null) return;
    const dw = hg === ag, hp = dw ? 1 : hg > ag ? 3 : 0, ap = dw ? 1 : ag > hg ? 3 : 0;
    [[[h1,h2], hg, ag, hp], [[a1,a2], ag, hg, ap]].forEach(([duo, gf, ga, pts]) => {
      duo.forEach(p => { const a = acc[p]; a.g++; a.pts += pts; a.gf += gf; a.ga += ga;
        if (dw) a.dr++; else if (gf > ga) a.w++; else a.l++; });
    });
  });
  t.acc = acc;
  if (t.t && t.t.length === t.size) {
    t.table = t.t.slice();                        // recorded order keeps the original tie-breaks
  } else {
    t.table = t.players.slice().sort((a, b) =>
      acc[b].pts - acc[a].pts || (acc[b].gf - acc[b].ga) - (acc[a].gf - acc[a].ga) || acc[b].gf - acc[a].gf);
  }
  t.place = {}; t.table.forEach((p, i) => { t.place[p] = i + 1; });
  t.legs = finalLegs(t);
  applyFinal(t);
  t.done = t.m.length > 0 && t.m.every(m => m[6] != null && m[7] != null) && t.c && t.c.length === 2;
  t.top2 = t.c && t.c.length === 2 &&
    ((t.c[0] === t.table[0] && t.c[1] === t.table[1]) || (t.c[0] === t.table[1] && t.c[1] === t.table[0]));
  return t;
}

function aggregate(list) {
  const S = Array.from({ length: NP }, () => ({ app:0, g:0, w:0, dr:0, l:0, pts:0, gf:0, ga:0, titles:0, finals:0, last:0, places:[0,0,0,0,0,0] }));
  const PAIR = {};
  /* every match a player played, in order — the raw material for streaks,
     form, the home-and-away split and the chemistry baseline */
  const LOG = Array.from({ length: NP }, () => []);
  const DUEL = {};          // pair against pair
  const H2H = Array.from({ length: NP }, () => Array.from({ length: NP }, () => ({ g:0, w:0, dr:0, l:0, gf:0, ga:0 })));
  const TEAM = CLUBS.map(() => ({ drawn:0, titles:0, finals:0, g:0, w:0, dr:0, l:0, gf:0, ga:0 }));
  const perT = Array.from({ length: NP }, () => ({}));
  let goals = 0, matches = 0, draws = 0;
  const pairRec = (a, b) => {
    const k = Math.min(a, b) + "-" + Math.max(a, b);
    return PAIR[k] || (PAIR[k] = { a:Math.min(a,b), b:Math.max(a,b), g:0, w:0, dr:0, l:0, gf:0, ga:0, titles:0 });
  };

  list.forEach(t => {
    t.players.forEach(p => { S[p].app++; TEAM[t.teamOf[p]].drawn++; });
    t.table.forEach((p, i) => { if (i < 6) S[p].places[i]++; if (i === t.size - 1) S[p].last++; });
    t.table.slice(0, 4).forEach(p => { S[p].finals++; TEAM[t.teamOf[p]].finals++; });
    t.c.forEach(p => { S[p].titles++; TEAM[t.teamOf[p]].titles++; });
    pairRec(t.c[0], t.c[1]).titles++;

    t.m.forEach((m, mi) => {
      const [h1, h2, ht, a1, a2, at, hg, ag] = m;
      goals += hg + ag; matches++;
      const dw = hg === ag; if (dw) draws++;
      const hp = dw ? 1 : hg > ag ? 3 : 0, ap = dw ? 1 : ag > hg ? 3 : 0;
      [[[h1,h2], ht, hg, ag, hp, true,  [a1,a2], at],
       [[a1,a2], at, ag, hg, ap, false, [h1,h2], ht]].forEach(([duo, club, gf, ga, pts, home, opp, oclub]) => {
        const won = gf > ga;
        duo.forEach(p => { const s = S[p]; s.g++; s.pts += pts; s.gf += gf; s.ga += ga;
          if (dw) s.dr++; else if (won) s.w++; else s.l++; });
        const pr = pairRec(duo[0], duo[1]);
        pr.g++; pr.gf += gf; pr.ga += ga; if (dw) pr.dr++; else if (won) pr.w++; else pr.l++;
        const T_ = TEAM[club]; T_.g++; T_.gf += gf; T_.ga += ga;
        if (dw) T_.dr++; else if (won) T_.w++; else T_.l++;
        duo.forEach((p, ix) => LOG[p].push({
          ti: t.i, num: t.num, mi, club, oclub, gf, ga, pts, home,
          res: dw ? "d" : won ? "w" : "l", mate: duo[1 - ix], opp: opp.slice()
        }));
      });
      /* the two pairs met: record it from both sides */
      const kh = pairKey(h1, h2), ka = pairKey(a1, a2);
      const dRec = (x, y) => DUEL[x + "|" + y] ||
        (DUEL[x + "|" + y] = { x, y, xa: Math.min(h1, h2), g: 0, w: 0, dr: 0, l: 0, gf: 0, ga: 0 });
      const DA = dRec(kh, ka), DB = dRec(ka, kh);
      DA.g++; DB.g++; DA.gf += hg; DA.ga += ag; DB.gf += ag; DB.ga += hg;
      if (dw) { DA.dr++; DB.dr++; } else if (hg > ag) { DA.w++; DB.l++; } else { DA.l++; DB.w++; }
      [h1, h2].forEach(x => [a1, a2].forEach(y => {
        const A = H2H[x][y], B = H2H[y][x];
        A.g++; B.g++; A.gf += hg; A.ga += ag; B.gf += ag; B.ga += hg;
        if (dw) { A.dr++; B.dr++; } else if (hg > ag) { A.w++; B.l++; } else { A.l++; B.w++; }
      }));
    });
    t.players.forEach(p => {
      perT[p][t.i] = Object.assign({}, t.acc[p], { place: t.place[p], champ: t.c.includes(p), club: t.teamOf[p], size: t.size });
    });
  });

  const MAXAPP = Math.max(1, ...S.map(s => s.app));
  S.forEach((s, i) => {
    s.i = i; s.gd = s.gf - s.ga; s.ppg = s.g ? s.pts / s.g : 0; s.k = s.app ? MAXAPP / s.app : 1;
    s.avgPlace = s.app ? s.places.reduce((a, c, j) => a + c * (j + 1), 0) / s.app : 0;
    s.titleRate = s.app ? s.titles / s.app : 0;
  });
  Object.values(PAIR).forEach(p => { p.pts = p.w * 3 + p.dr; p.ppg = p.g ? p.pts / p.g : 0; p.gd = p.gf - p.ga; });

  /* Chemistry: a pair's points per match against what those same two manage
     when they are NOT together. Excluding their shared matches from each
     player's own rate keeps the comparison from measuring itself. */
  const CHEM = {};
  const apartRate = (p, q) => {
    let g = 0, pts = 0;
    LOG[p].forEach(e => { if (e.mate !== q) { g++; pts += e.pts; } });
    return g ? pts / g : 0;
  };
  Object.keys(PAIR).forEach(k => {
    const pr = PAIR[k];
    const exp = (apartRate(pr.a, pr.b) + apartRate(pr.b, pr.a)) / 2;
    let s2 = 0;
    LOG[pr.a].forEach(e => { if (e.mate === pr.b) s2 += (e.pts - pr.ppg) * (e.pts - pr.ppg); });
    const se = pr.g > 1 ? Math.sqrt(s2 / (pr.g - 1) / pr.g) : 0;
    const d = pr.ppg - exp;
    CHEM[k] = { a: pr.a, b: pr.b, g: pr.g, act: pr.ppg, exp, d, se, solid: se > 0 && Math.abs(d) > 1.5 * se };
  });
  TEAM.forEach((t, i) => { t.name = CLUBS[i]; t.gd = t.gf - t.ga; t.pts = t.w * 3 + t.dr; t.ppg = t.g ? t.pts / t.g : 0; });
  const ORDER = S.map(s => s.i).sort((a, b) => S[b].pts - S[a].pts || S[b].titles - S[a].titles);
  computeOVR(S);
  return { S, PAIR, H2H, TEAM, perT, ORDER, MAXAPP, goals, matches, draws, list, LOG, DUEL, CHEM };
}

function rebuild() {
  const seen = {};
  SEED.T.forEach(t => {
    seen[t.i] = { i: t.i, num: t.i, season: 0, d: t.d.map(x => x.slice()), t: t.t.slice(),
                  m: t.m.map(x => x.slice()), c: t.c.slice(), seed: true };
  });
  Object.values(LIVE).forEach(t => { seen[t.i] = t; });
  TS = Object.values(seen).sort((a, b) => a.i - b.i).map(decorate);
  if (SCOPE !== "all" && !SEASONS.some(s => s.id === SCOPE)) SCOPE = latestSeason();
  TSS = SCOPE === "all" ? TS : TS.filter(t => t.season === SCOPE);

  const A = aggregate(TSS.filter(t => t.done));
  S = A.S; PAIR = A.PAIR; H2H = A.H2H; TEAM = A.TEAM; perT = A.perT; ORDER = A.ORDER; MAXAPP = A.MAXAPP;
  LOG = A.LOG; DUEL = A.DUEL; CHEM = A.CHEM;
  totGoals = A.goals; totMatches = A.matches; drawnMatches = A.draws;
  LAST = A.list[A.list.length - 1] || null;

  /* a season that has not started yet borrows the previous one's cards */
  buildModel();

  CARRY = null;
  if (SCOPE !== "all" && !A.list.length) {
    const earlier = TS.filter(t => t.done && t.season < SCOPE);
    if (earlier.length) {
      const pid = Math.max.apply(null, earlier.map(t => t.season));
      CARRY = { name: seasonById(pid).name, agg: aggregate(earlier.filter(t => t.season === pid)) };
    }
  }
}
const pairKey = (a, b) => Math.min(a, b) + "-" + Math.max(a, b);

/* The two legs of the final, derived from the league table.
   Leg 1: places 3+4 host with the club of place 4, against places 1+2 with the
   club of place 2. Leg 2: places 1+2 host with the club of place 1, against
   places 3+4 with the club of place 3. */
function finalLegs(t) {
  const tb = t.table;
  if (!tb || tb.length < 4) return null;
  const sc = (t.rec && t.rec.final) || [[null, null], [null, null]];
  const g = i => (sc[i] && sc[i].length === 2) ? sc[i] : [null, null];
  return [
    { n: 1, home: [tb[2], tb[3]], hc: t.teamOf[tb[3]], away: [tb[0], tb[1]], ac: t.teamOf[tb[1]], s: g(0) },
    { n: 2, home: [tb[0], tb[1]], hc: t.teamOf[tb[0]], away: [tb[2], tb[3]], ac: t.teamOf[tb[2]], s: g(1) }
  ];
}
/* The winners follow from the aggregate. Level on aggregate, the golden-goal
   pick stored on the record decides. Tournaments with no `final` field at all
   keep whatever champions they were recorded with. */
/* A deep, writable copy. Records hold nothing but numbers, strings and
   arrays, so a JSON round-trip is both sufficient and exact. */
function thaw(o) {
  try { return JSON.parse(JSON.stringify(o)); } catch (e) { return o; }
}
function frozenRec(r) {
  return !!r && (Object.isFrozen(r) ||
    (r.scores && Object.isFrozen(r.scores)) ||
    (r.clubs && Object.isFrozen(r.clubs)) ||
    (r.final && Object.isFrozen(r.final)));
}
/* Every edit writes into t.rec in place. If that record is frozen the write
   throws and the edit is lost, so swap in a writable copy first — and point
   the live object at the same copy, so the two can never drift apart. */
function writable(t) {
  if (!t || !frozenRec(t.rec)) return t;
  const cp = thaw(t.rec);
  t.rec = cp;
  try { if (LIVE[t.i] && LIVE[t.i] !== t) LIVE[t.i].rec = cp; } catch (e) {}
  return t;
}

function applyFinal(t) {
  if (!t.rec || !t.rec.final || !t.legs) return;
  writable(t);
  const L = t.legs;
  if (!L.every(l => l.s[0] != null && l.s[1] != null)) { t.c = []; t.rec.champs = []; return; }
  const top = L[0].s[1] + L[1].s[0], bot = L[0].s[0] + L[1].s[1];
  if (top > bot) t.c = [t.table[0], t.table[1]].slice().sort((a, b) => a - b);
  else if (bot > top) t.c = [t.table[2], t.table[3]].slice().sort((a, b) => a - b);
  else t.c = t.rec.gg ? (t.rec.champs || []).slice().sort((a, b) => a - b) : [];
  t.rec.champs = t.c.slice();
}

const legMatch = L => [L.home[0], L.home[1], L.hc, L.away[0], L.away[1], L.ac, L.s[0], L.s[1]];

/* Aggregate over the two legs. Pair 1-2 is away in leg 1 and home in leg 2. */
function finalOutcome(t) {
  const L = t.legs;
  if (!L) return null;
  const played = L.every(l => l.s[0] != null && l.s[1] != null);
  if (!played) return { L: L, played: false };
  const top = L[0].s[1] + L[1].s[0];
  const bot = L[0].s[0] + L[1].s[1];
  const tb = t.table;
  return { L: L, played: true, top: top, bot: bot,
           winner: top > bot ? [tb[0], tb[1]] : bot > top ? [tb[2], tb[3]] : null };
}

/* render one view against a different season's aggregate */
function withAgg(agg, fn, host) {
  const keep = { S, PAIR, H2H, TEAM, perT, ORDER, MAXAPP, TSS, LOG, DUEL, CHEM };
  S = agg.S; PAIR = agg.PAIR; H2H = agg.H2H; TEAM = agg.TEAM;
  perT = agg.perT; ORDER = agg.ORDER; MAXAPP = agg.MAXAPP; TSS = agg.list;
  LOG = agg.LOG; DUEL = agg.DUEL; CHEM = agg.CHEM;
  try { fn(host); } finally {
    S = keep.S; PAIR = keep.PAIR; H2H = keep.H2H; TEAM = keep.TEAM;
    perT = keep.perT; ORDER = keep.ORDER; MAXAPP = keep.MAXAPP; TSS = keep.TSS;
    LOG = keep.LOG; DUEL = keep.DUEL; CHEM = keep.CHEM;
  }
}

/* ---------- the card rating ----------
   Four career measures, each scaled 0-1 across the six players, then blended
   and mapped onto 62-93 so the cards read like a squad list. Every input is
   shown on the card, so the number can always be traced back. */
/* ---------- achievements ----------
   Unlocked by walking every tournament in order, match by match: streaks,
   clean sheets, big wins, milestones, titles. Each one remembers the
   tournament where it was first earned. Also run by the push server, which
   compares before and after a result to announce new ones. */
const ACH = [
  { id: "g100", icon: "🎮", name: "100 משחקים", desc: "שיחק 100 משחקים" },
  { id: "g250", icon: "🕹️", name: "250 משחקים", desc: "שיחק 250 משחקים" },
  { id: "g500", icon: "👾", name: "500 משחקים", desc: "שיחק 500 משחקים" },
  { id: "w3", icon: "🔥", name: "שלושה ברצף", desc: "3 ניצחונות רצופים" },
  { id: "w5", icon: "⚡", name: "חמישה ברצף", desc: "5 ניצחונות רצופים" },
  { id: "w8", icon: "🌪️", name: "בלתי ניתן לעצירה", desc: "8 ניצחונות רצופים" },
  { id: "u10", icon: "🛡️", name: "עשרה בלי הפסד", desc: "10 משחקים רצופים בלי הפסד" },
  { id: "cs1", icon: "🧤", name: "רשת נקייה", desc: "משחק בלי לספוג" },
  { id: "cs25", icon: "🧱", name: "חומה", desc: "25 משחקים בלי לספוג" },
  { id: "big4", icon: "💥", name: "דריסה", desc: "ניצחון בהפרש 4 ומעלה" },
  { id: "big6", icon: "☄️", name: "השפלה", desc: "ניצחון בהפרש 6 ומעלה" },
  { id: "gf6", icon: "🎯", name: "מטווח", desc: "6 שערים במשחק אחד" },
  { id: "top", icon: "📈", name: "ראש הטבלה", desc: "סיים ראשון בשלב הליגה" },
  { id: "unb", icon: "🧘", name: "בלי הפסד", desc: "שלב ליגה שלם בלי להפסיד" },
  { id: "perf", icon: "💎", name: "טורניר מושלם", desc: "ניצח בכל משחקי הליגה שלו" },
  { id: "gk", icon: "⚽", name: "מלך השערים", desc: "הכי הרבה שערים בטורניר" },
  { id: "t1", icon: "🏆", name: "אליפות ראשונה", desc: "זכה בטורניר" },
  { id: "t5", icon: "🥇", name: "חמש אליפויות", desc: "זכה ב־5 טורנירים" },
  { id: "t10", icon: "👑", name: "עשר אליפויות", desc: "זכה ב־10 טורנירים" },
  { id: "tt2", icon: "✌️", name: "פעמיים ברצף", desc: "אלוף בשני טורנירים רצופים" },
  { id: "tt3", icon: "🔱", name: "שלוש ברצף", desc: "אלוף בשלושה טורנירים רצופים" }
];
function achievements() {
  const got = {};
  for (let p = 0; p < NP; p++) got[p] = {};
  const st = {};
  for (let p = 0; p < NP; p++) st[p] = { g: 0, w: 0, u: 0, cs: 0, titles: 0, lastTitle: -9, run: 0 };
  const give = (p, id, t) => { if (!got[p][id]) got[p][id] = { t: t.num, season: t.season }; };
  let doneIdx = 0;
  TS.forEach(t => {
    t.m.forEach(m => {
      if (m[6] == null || m[7] == null) return;
      [[[m[0], m[1]], m[6], m[7]], [[m[3], m[4]], m[7], m[6]]].forEach(([duo, gf, ga]) => duo.forEach(p => {
        const s = st[p]; if (!s) return;
        s.g++;
        if (gf > ga) { s.w++; s.u++; } else if (gf === ga) { s.w = 0; s.u++; } else { s.w = 0; s.u = 0; }
        if (ga === 0) s.cs++;
        if (s.g >= 100) give(p, "g100", t); if (s.g >= 250) give(p, "g250", t); if (s.g >= 500) give(p, "g500", t);
        if (s.w >= 3) give(p, "w3", t); if (s.w >= 5) give(p, "w5", t); if (s.w >= 8) give(p, "w8", t);
        if (s.u >= 10) give(p, "u10", t);
        if (s.cs >= 1) give(p, "cs1", t); if (s.cs >= 25) give(p, "cs25", t);
        if (gf - ga >= 4) give(p, "big4", t); if (gf - ga >= 6) give(p, "big6", t);
        if (gf >= 6) give(p, "gf6", t);
      }));
    });
    if (!t.done) return;
    const idx = doneIdx++;
    if (t.table && t.table.length) give(t.table[0], "top", t);
    t.players.forEach(p => {
      const a = t.acc[p]; if (!a || !a.g) return;
      if (a.l === 0) give(p, "unb", t);
      if (a.w === a.g) give(p, "perf", t);
    });
    const best = Math.max.apply(null, t.players.map(p => t.acc[p].gf));
    const kings = t.players.filter(p => t.acc[p].gf === best);
    if (kings.length === 1) give(kings[0], "gk", t);
    (t.c || []).forEach(p => {
      const s = st[p]; if (!s) return;
      s.titles++;
      s.run = s.lastTitle === idx - 1 ? s.run + 1 : 1;
      s.lastTitle = idx;
      give(p, "t1", t);
      if (s.titles >= 5) give(p, "t5", t); if (s.titles >= 10) give(p, "t10", t);
      if (s.run >= 2) give(p, "tt2", t); if (s.run >= 3) give(p, "tt3", t);
    });
  });
  return got;
}


function computeOVR(S) {
  const ax = [
    { k: "ppg",  w: .34, v: s => s.ppg },
    { k: "ttl",  w: .30, v: s => s.titleRate },
    { k: "fin",  w: .16, v: s => (s.app ? s.finals / s.app : 0) },
    { k: "gd",   w: .20, v: s => (s.g ? (s.gf - s.ga) / s.g : 0) }
  ];
  ax.forEach(a => { a.lo = Math.min(...S.map(a.v)); a.hi = Math.max(...S.map(a.v)); });
  S.forEach(s => {
    let z = 0;
    ax.forEach(a => { z += a.w * (a.hi > a.lo ? (a.v(s) - a.lo) / (a.hi - a.lo) : .5); });
    s.ovr = Math.round(62 + 31 * z);
    s.tier = s.ovr >= 84 ? "gold" : s.ovr >= 74 ? "silver" : "bronze";
    s.role = s.gf / Math.max(1, s.g) >= s.ga / Math.max(1, s.g) ? "התקפה" : "הגנה";
  });
}

function hydrate(rec) {
  const season = rec.s || 0;
  const num = rec.n || rec.i;
  const tpl = TPL[rec.tpl] || TPL[String(rec.slots.length)];
  const slots = rec.slots, clubs = rec.clubs;
  const d = slots.map((p, i) => [p, clubIdx(clubs[i])]);
  const m = tpl.map((f, k) => {
    const sc = (rec.scores && rec.scores[k]) || [null, null];
    return [slots[f.h[0] - 1], slots[f.h[1] - 1], clubIdx(clubs[f.hc - 1]),
            slots[f.a[0] - 1], slots[f.a[1] - 1], clubIdx(clubs[f.ac - 1]),
            sc[0], sc[1]];
  });
  return { i: uid(season, num), num, season, d, t: null, m,
           c: (rec.champs || []).slice().sort((a, b) => a - b), rec, live: true };
}
/* keep each match row's cloud label in step with the store */

let MODEL = null;
const SHRINK = 25;      // matches of league-average evidence mixed into every rate
const CLUB_W = 0.25;    // how much the club counts next to the pair

function buildModel() {
  const done = TS.filter(t => t.done);
  const all = aggregate(done);
  const mu = all.matches ? all.goals / (2 * all.matches) : 2.2;
  const rate = (v, g) => (v + SHRINK * mu) / (g + SHRINK) / mu;
  const pf = {}, cf = {}, vs = {};
  Object.values(all.PAIR).forEach(p => {
    pf[p.a + "-" + p.b] = { att: rate(p.gf, p.g), def: rate(p.ga, p.g), g: p.g, ppg: p.ppg,
                            w: p.w, d: p.dr, l: p.l, gf: p.gf, ga: p.ga };
  });
  all.TEAM.forEach((t, i) => {
    if (t.g) cf[i] = { att: rate(t.gf, t.g), def: rate(t.ga, t.g), g: t.g, name: CLUBS[i] };
  });
  /* how these two exact pairs have fared against each other before */
  const side = (a, b) => Math.min(a, b) + "-" + Math.max(a, b);
  done.forEach(t => t.m.forEach(m => {
    const A = side(m[0], m[1]), B = side(m[3], m[4]);
    const put = (x, y, gf, ga) => {
      const k = x + "|" + y;
      const r = vs[k] || (vs[k] = { g: 0, w: 0, d: 0, l: 0, gf: 0, ga: 0 });
      r.g++; r.gf += gf; r.ga += ga;
      if (gf > ga) r.w++; else if (gf === ga) r.d++; else r.l++;
    };
    put(A, B, m[6], m[7]);
    put(B, A, m[7], m[6]);
  }));
  MODEL = { mu, pf, cf, vs, matches: all.matches, rho: 1 };
  MODEL.rho = calibrateDraw(done);
}

function poissonRow(lambda, n) {
  const out = []; let p = Math.exp(-lambda);
  for (let k = 0; k <= n; k++) { out.push(p); p = p * lambda / (k + 1); }
  return out;
}

/* expected goals for both sides of any pairing, clubs included */
function lambdasFor(h1, h2, hc, a1, a2, ac) {
  if (!MODEL || !MODEL.matches) return null;
  const key = (a, b) => Math.min(a, b) + "-" + Math.max(a, b);
  const ph = MODEL.pf[key(h1, h2)], pa = MODEL.pf[key(a1, a2)];
  if (!ph || !pa) return null;
  const one = { att: 1, def: 1, g: 0 };
  const ch = MODEL.cf[hc] || one, ca = MODEL.cf[ac] || one;
  const mix = (x, c) => Math.pow(x, 1 - CLUB_W) * Math.pow(c, CLUB_W);
  return [MODEL.mu * mix(ph.att, ch.att) * mix(pa.def, ca.def),
          MODEL.mu * mix(pa.att, ca.att) * mix(ph.def, ch.def), ph, pa, ch, ca];
}

function rawForecast(m) {
  const L = lambdasFor(m[0], m[1], m[2], m[3], m[4], m[5]);
  if (!L) return null;
  const key = (a, b) => Math.min(a, b) + "-" + Math.max(a, b);
  const kh = key(m[0], m[1]), ka = key(m[3], m[4]);
  const lh = L[0], la = L[1], ph = L[2], pa = L[3], ch = L[4], ca = L[5];
  const N = 12, A = poissonRow(lh, N), B = poissonRow(la, N);
  let w = 0, d = 0, l = 0;
  for (let i = 0; i <= N; i++) for (let j = 0; j <= N; j++) {
    const q = A[i] * B[j];
    if (i > j) w += q; else if (i === j) d += q; else l += q;
  }
  return { w, d, l, lh, la, ph, pa, ch, ca, kh, ka };
}

function forecast(m) {
  const r = rawForecast(m);
  if (!r) return null;
  const rho = MODEL.rho || 1;
  const den = r.w + rho * r.d + r.l;
  return { w: r.w / den, d: rho * r.d / den, l: r.l / den,
           lh: r.lh, la: r.la, ph: r.ph, pa: r.pa, ch: r.ch, ca: r.ca,
           h2h: MODEL.vs[r.kh + "|" + r.ka] || null };
}

/* one shared factor on the drawn-score diagonal, solved so the model's mean
   draw probability equals the rate the archive actually shows */
function calibrateDraw(done) {
  const cells = [];
  let draws = 0, n = 0;
  done.forEach(t => t.m.forEach(m => {
    n++; if (m[6] === m[7]) draws++;
    const r = rawForecast(m);
    if (r) cells.push([r.d, r.w + r.l]);
  }));
  if (!n || !cells.length) return 1;
  const target = draws / n;
  const mean = rho => cells.reduce((s, c) => s + rho * c[0] / (rho * c[0] + c[1]), 0) / cells.length;
  let lo = 0.25, hi = 6;
  for (let k = 0; k < 40; k++) {
    const mid = (lo + hi) / 2;
    if (mean(mid) < target) lo = mid; else hi = mid;
  }
  return (lo + hi) / 2;
}


function rng(seed) {
  let x = seed | 0 || 123456789;
  return () => {
    x ^= x << 13; x |= 0; x ^= x >>> 17; x ^= x << 5; x |= 0;
    return ((x >>> 0) % 100000) / 100000;
  };
}
function seedOf(t) {
  let h = 2166136261 ^ t.i;
  t.m.forEach(m => { h = Math.imul(h ^ ((m[6] == null ? 99 : m[6]) * 31 + (m[7] == null ? 99 : m[7])), 16777619); });
  return h >>> 0;
}
function samplePoisson(lambda, rnd) {
  const L = Math.exp(-lambda);
  let k = 0, p = 1;
  do { k++; p *= rnd(); } while (p > L && k < 40);
  return k - 1;
}

/* the final's two legs, as expected goals, for the newsroom preview */
function finalLegLambdas(t, tb) {
  const A = lambdasFor(tb[2], tb[3], t.teamOf[tb[3]], tb[0], tb[1], t.teamOf[tb[1]]);
  const B = lambdasFor(tb[0], tb[1], t.teamOf[tb[0]], tb[2], tb[3], t.teamOf[tb[2]]);
  return [A, B];
}

/* `force` optionally pins the first unplayed fixture to an outcome
   ("h" | "d" | "a") so we can ask what one result would be worth */
/* The same tournament state always simulates to the same numbers (the
   stream is seeded from it), so the answer is kept: reopening the newsroom
   or a tournament costs nothing the second time. The key covers everything
   the result depends on — scores, clubs, the model, and the options. */
const SIMC = { model: null, map: {}, n: 0 };
function simulate(t, iters, force, seed) {
  if (!MODEL || !MODEL.matches) return null;
  if (SIMC.model !== MODEL || SIMC.n > 600) { SIMC.model = MODEL; SIMC.map = {}; SIMC.n = 0; }
  const key = scoreSig(t) + "|" + t.d.map(x => x[1]).join(".") + "|" + iters + "|" +
              (force ? (typeof force === "string" ? force : force.o + "@" + force.at) : "-") + "|" +
              (seed != null ? seed : "s");
  if (SIMC.map[key]) return SIMC.map[key];
  const out = simulateRun(t, iters, force, seed);
  if (out) { SIMC.map[key] = out; SIMC.n++; }
  return out;
}
function simulateRun(t, iters, force, seed) {
  if (!MODEL || !MODEL.matches) return null;
  /* `force` is "h"|"d"|"a" for the next open fixture, or {o, at} to pin one
     particular fixture. `seed` pins the stream, so two runs of neighbouring
     states differ because of the football and not because of the dice. */
  const fo = typeof force === "string" ? { o: force, at: -1 } : (force || null);
  const players = t.players;
  const base = {};
  players.forEach(p => { base[p] = { pts: 0, gf: 0, ga: 0 }; });
  const open = [];
  t.m.forEach((m, mi) => {
    if (m[6] != null && m[7] != null) {
      addResult(base, m, m[6], m[7]);
    } else {
      const f = rawForecast(m);
      open.push({ m, at: mi, lh: f ? f.lh : MODEL.mu, la: f ? f.la : MODEL.mu });
    }
  });
  if (fo && fo.at >= 0 && !open.some(o => o.at === fo.at)) return null;   // already played
  const out = {};
  players.forEach(p => { out[p] = { place: [0,0,0,0,0,0], top4: 0, title: 0, first: 0 }; });
  const rnd = rng((seed != null ? seed : seedOf(t)) +
                  (fo ? fo.o.charCodeAt(0) * 7919 + (fo.at + 2) * 104729 : 0));
  for (let it = 0; it < iters; it++) {
    const acc = {};
    players.forEach(p => { acc[p] = { pts: base[p].pts, gf: base[p].gf, ga: base[p].ga }; });
    open.forEach((o, oi) => {
      let hg, ag;
      if (fo && (fo.at < 0 ? oi === 0 : o.at === fo.at)) {
        do { hg = samplePoisson(o.lh, rnd); ag = samplePoisson(o.la, rnd); }
        while (!((fo.o === "h" && hg > ag) || (fo.o === "d" && hg === ag) || (fo.o === "a" && ag > hg)));
      } else {
        hg = samplePoisson(o.lh, rnd); ag = samplePoisson(o.la, rnd);
      }
      addResult(acc, o.m, hg, ag);
    });
    const order = players.slice().sort((a, b) =>
      acc[b].pts - acc[a].pts ||
      (acc[b].gf - acc[b].ga) - (acc[a].gf - acc[a].ga) ||
      acc[b].gf - acc[a].gf);
    order.forEach((p, i) => { if (i < 6) out[p].place[i]++; if (i < 4) out[p].top4++; });
    out[order[0]].first++;
    if (order.length >= 4) {
      const A = lambdasFor(order[2], order[3], t.teamOf[order[3]],
                           order[0], order[1], t.teamOf[order[1]]);
      const B = lambdasFor(order[0], order[1], t.teamOf[order[0]],
                           order[2], order[3], t.teamOf[order[2]]);
      let topG, botG;
      if (A && B) {
        const l1h = samplePoisson(A[0], rnd), l1a = samplePoisson(A[1], rnd);
        const l2h = samplePoisson(B[0], rnd), l2a = samplePoisson(B[1], rnd);
        topG = l1a + l2h; botG = l1h + l2a;
      } else { topG = 0; botG = 0; }
      const top = topG > botG || (topG === botG && rnd() < 0.5);
      const win = top ? [order[0], order[1]] : [order[2], order[3]];
      win.forEach(p => out[p].title++);
    }
  }
  players.forEach(p => {
    const o = out[p];
    o.top4 /= iters; o.title /= iters; o.first /= iters;
    o.place = o.place.map(c => c / iters);
  });
  return out;
}

function addResult(acc, m, hg, ag) {
  const dw = hg === ag, hp = dw ? 1 : hg > ag ? 3 : 0, ap = dw ? 1 : ag > hg ? 3 : 0;
  [[[m[0], m[1]], hg, ag, hp], [[m[3], m[4]], ag, hg, ap]].forEach(([duo, gf, ga, pts]) => {
    duo.forEach(p => { const a = acc[p]; a.pts += pts; a.gf += gf; a.ga += ga; });
  });
}

/* ==========================================================================
   The timeline: the tournament at every stage it passed through
   --------------------------------------------------------------------------
   Standings are derived and never stored, so the tournament after N matches
   is simply the same tournament with the later results blanked out. Running
   the simulation at each stage, all from one pinned seed, gives the road to
   the final as it looked at that moment — and the difference between two
   consecutive stages is exactly what that one result was worth.
   ========================================================================== */
const scoreSig = t => t.i + ":" + t.m.map(m =>
  (m[6] == null ? "-" : m[6]) + "." + (m[7] == null ? "-" : m[7])).join(",");

function snapshotAt(t, k) {
  return decorate({
    i: t.i, num: t.num, season: t.season,
    d: t.d.map(x => x.slice()), t: null,
    m: t.m.map((row, i) => i < k ? row.slice() : row.slice(0, 6).concat([null, null])),
    c: [], rec: { i: t.i, scores: [] }, snap: true
  });
}

/* ==========================================================================
   Heavy work, a step at a time
   --------------------------------------------------------------------------
   A phone runs these simulations 4-8x slower than a laptop. Run as one block,
   the season-long forecast froze a phone for ten seconds and the tabs looked
   dead. So every job that runs many simulations is done one unit at a time,
   handing the browser back between units: a tap waits for one unit, never
   for the whole job. Callers that cannot wait read only what is cached.
   ========================================================================== */
